<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `dbpropinsi`
//

// `dbpropinsi`.`kabupaten`
$kabupaten = array(
  array('id_kabupaten' => '1','id_propinsi' => '20','kabupaten' => 'Aceh Barat'),
  array('id_kabupaten' => '2','id_propinsi' => '20','kabupaten' => 'Aceh Barat Daya'),
  array('id_kabupaten' => '3','id_propinsi' => '20','kabupaten' => 'Aceh Besar'),
  array('id_kabupaten' => '4','id_propinsi' => '20','kabupaten' => 'Aceh Jaya'),
  array('id_kabupaten' => '5','id_propinsi' => '20','kabupaten' => 'Aceh Selatan'),
  array('id_kabupaten' => '6','id_propinsi' => '20','kabupaten' => 'Aceh Singkil'),
  array('id_kabupaten' => '7','id_propinsi' => '20','kabupaten' => 'Aceh Tamiang'),
  array('id_kabupaten' => '8','id_propinsi' => '20','kabupaten' => 'Aceh Tengah'),
  array('id_kabupaten' => '9','id_propinsi' => '20','kabupaten' => 'Aceh Tenggara'),
  array('id_kabupaten' => '10','id_propinsi' => '20','kabupaten' => 'Aceh Timur'),
  array('id_kabupaten' => '11','id_propinsi' => '20','kabupaten' => 'Aceh Utara'),
  array('id_kabupaten' => '12','id_propinsi' => '31','kabupaten' => 'Agam'),
  array('id_kabupaten' => '13','id_propinsi' => '22','kabupaten' => 'Alor'),
  array('id_kabupaten' => '14','id_propinsi' => '18','kabupaten' => 'Ambon'),
  array('id_kabupaten' => '15','id_propinsi' => '33','kabupaten' => 'Asahan'),
  array('id_kabupaten' => '16','id_propinsi' => '23','kabupaten' => 'Asmat'),
  array('id_kabupaten' => '17','id_propinsi' => '1','kabupaten' => 'Badung'),
  array('id_kabupaten' => '18','id_propinsi' => '13','kabupaten' => 'Balangan'),
  array('id_kabupaten' => '19','id_propinsi' => '15','kabupaten' => 'Balikpapan'),
  array('id_kabupaten' => '20','id_propinsi' => '20','kabupaten' => 'Banda Aceh'),
  array('id_kabupaten' => '21','id_propinsi' => '17','kabupaten' => 'Bandar Lampung'),
  array('id_kabupaten' => '22','id_propinsi' => '9','kabupaten' => 'Bandung'),
  array('id_kabupaten' => '23','id_propinsi' => '9','kabupaten' => 'Bandung Barat'),
  array('id_kabupaten' => '24','id_propinsi' => '28','kabupaten' => 'Banggai'),
  array('id_kabupaten' => '25','id_propinsi' => '28','kabupaten' => 'Banggai Kepulauan'),
  array('id_kabupaten' => '26','id_propinsi' => '2','kabupaten' => 'Bangka'),
  array('id_kabupaten' => '27','id_propinsi' => '2','kabupaten' => 'Bangka Barat'),
  array('id_kabupaten' => '28','id_propinsi' => '2','kabupaten' => 'Bangka Selatan'),
  array('id_kabupaten' => '29','id_propinsi' => '2','kabupaten' => 'Bangka Tengah'),
  array('id_kabupaten' => '30','id_propinsi' => '11','kabupaten' => 'Bangkalan'),
  array('id_kabupaten' => '31','id_propinsi' => '1','kabupaten' => 'Bangli'),
  array('id_kabupaten' => '32','id_propinsi' => '9','kabupaten' => 'Banjar'),
  array('id_kabupaten' => '33','id_propinsi' => '13','kabupaten' => 'Banjarbaru'),
  array('id_kabupaten' => '34','id_propinsi' => '13','kabupaten' => 'Banjarmasin'),
  array('id_kabupaten' => '35','id_propinsi' => '10','kabupaten' => 'Banjarnegara'),
  array('id_kabupaten' => '36','id_propinsi' => '27','kabupaten' => 'Bantaeng'),
  array('id_kabupaten' => '37','id_propinsi' => '5','kabupaten' => 'Bantul'),
  array('id_kabupaten' => '38','id_propinsi' => '32','kabupaten' => 'Banyuasin'),
  array('id_kabupaten' => '39','id_propinsi' => '10','kabupaten' => 'Banyumas'),
  array('id_kabupaten' => '40','id_propinsi' => '11','kabupaten' => 'Banyuwangi'),
  array('id_kabupaten' => '41','id_propinsi' => '13','kabupaten' => 'Barito Kuala'),
  array('id_kabupaten' => '42','id_propinsi' => '14','kabupaten' => 'Barito Selatan'),
  array('id_kabupaten' => '43','id_propinsi' => '14','kabupaten' => 'Barito Timur'),
  array('id_kabupaten' => '44','id_propinsi' => '14','kabupaten' => 'Barito Utara'),
  array('id_kabupaten' => '45','id_propinsi' => '27','kabupaten' => 'Barru'),
  array('id_kabupaten' => '46','id_propinsi' => '16','kabupaten' => 'Batam'),
  array('id_kabupaten' => '47','id_propinsi' => '10','kabupaten' => 'Batang'),
  array('id_kabupaten' => '48','id_propinsi' => '8','kabupaten' => 'Batang Hari'),
  array('id_kabupaten' => '49','id_propinsi' => '11','kabupaten' => 'Batu'),
  array('id_kabupaten' => '50','id_propinsi' => '33','kabupaten' => 'Batu Bara'),
  array('id_kabupaten' => '51','id_propinsi' => '29','kabupaten' => 'Bau-Bau'),
  array('id_kabupaten' => '52','id_propinsi' => '9','kabupaten' => 'Bekasi'),
  array('id_kabupaten' => '53','id_propinsi' => '2','kabupaten' => 'Belitung'),
  array('id_kabupaten' => '54','id_propinsi' => '2','kabupaten' => 'Belitung Timur'),
  array('id_kabupaten' => '55','id_propinsi' => '22','kabupaten' => 'Belu'),
  array('id_kabupaten' => '56','id_propinsi' => '20','kabupaten' => 'Bener Meriah'),
  array('id_kabupaten' => '57','id_propinsi' => '25','kabupaten' => 'Bengkalis'),
  array('id_kabupaten' => '58','id_propinsi' => '12','kabupaten' => 'Bengkayang'),
  array('id_kabupaten' => '59','id_propinsi' => '4','kabupaten' => 'Bengkulu'),
  array('id_kabupaten' => '60','id_propinsi' => '4','kabupaten' => 'Bengkulu Selatan'),
  array('id_kabupaten' => '61','id_propinsi' => '4','kabupaten' => 'Bengkulu Tengah'),
  array('id_kabupaten' => '62','id_propinsi' => '4','kabupaten' => 'Bengkulu Utara'),
  array('id_kabupaten' => '63','id_propinsi' => '15','kabupaten' => 'Berau'),
  array('id_kabupaten' => '64','id_propinsi' => '23','kabupaten' => 'Biak Numfor'),
  array('id_kabupaten' => '65','id_propinsi' => '21','kabupaten' => 'Bima'),
  array('id_kabupaten' => '66','id_propinsi' => '33','kabupaten' => 'Binjai'),
  array('id_kabupaten' => '67','id_propinsi' => '16','kabupaten' => 'Bintan'),
  array('id_kabupaten' => '68','id_propinsi' => '20','kabupaten' => 'Bireuen'),
  array('id_kabupaten' => '69','id_propinsi' => '30','kabupaten' => 'Bitung'),
  array('id_kabupaten' => '70','id_propinsi' => '11','kabupaten' => 'Blitar'),
  array('id_kabupaten' => '71','id_propinsi' => '10','kabupaten' => 'Blora'),
  array('id_kabupaten' => '72','id_propinsi' => '7','kabupaten' => 'Boalemo'),
  array('id_kabupaten' => '73','id_propinsi' => '9','kabupaten' => 'Bogor'),
  array('id_kabupaten' => '74','id_propinsi' => '11','kabupaten' => 'Bojonegoro'),
  array('id_kabupaten' => '75','id_propinsi' => '30','kabupaten' => 'Bolaang Mongondow (Bolmong)'),
  array('id_kabupaten' => '76','id_propinsi' => '30','kabupaten' => 'Bolaang Mongondow Selatan'),
  array('id_kabupaten' => '77','id_propinsi' => '30','kabupaten' => 'Bolaang Mongondow Timur'),
  array('id_kabupaten' => '78','id_propinsi' => '30','kabupaten' => 'Bolaang Mongondow Utara'),
  array('id_kabupaten' => '79','id_propinsi' => '29','kabupaten' => 'Bombana'),
  array('id_kabupaten' => '80','id_propinsi' => '11','kabupaten' => 'Bondowoso'),
  array('id_kabupaten' => '81','id_propinsi' => '27','kabupaten' => 'Bone'),
  array('id_kabupaten' => '82','id_propinsi' => '7','kabupaten' => 'Bone Bolango'),
  array('id_kabupaten' => '83','id_propinsi' => '15','kabupaten' => 'Bontang'),
  array('id_kabupaten' => '84','id_propinsi' => '23','kabupaten' => 'Boven Digoel'),
  array('id_kabupaten' => '85','id_propinsi' => '10','kabupaten' => 'Boyolali'),
  array('id_kabupaten' => '86','id_propinsi' => '10','kabupaten' => 'Brebes'),
  array('id_kabupaten' => '87','id_propinsi' => '31','kabupaten' => 'Bukittinggi'),
  array('id_kabupaten' => '88','id_propinsi' => '1','kabupaten' => 'Buleleng'),
  array('id_kabupaten' => '89','id_propinsi' => '27','kabupaten' => 'Bulukumba'),
  array('id_kabupaten' => '90','id_propinsi' => '15','kabupaten' => 'Bulungan (Bulongan)'),
  array('id_kabupaten' => '91','id_propinsi' => '8','kabupaten' => 'Bungo'),
  array('id_kabupaten' => '92','id_propinsi' => '28','kabupaten' => 'Buol'),
  array('id_kabupaten' => '93','id_propinsi' => '18','kabupaten' => 'Buru'),
  array('id_kabupaten' => '94','id_propinsi' => '18','kabupaten' => 'Buru Selatan'),
  array('id_kabupaten' => '95','id_propinsi' => '29','kabupaten' => 'Buton'),
  array('id_kabupaten' => '96','id_propinsi' => '29','kabupaten' => 'Buton Utara'),
  array('id_kabupaten' => '97','id_propinsi' => '9','kabupaten' => 'Ciamis'),
  array('id_kabupaten' => '98','id_propinsi' => '9','kabupaten' => 'Cianjur'),
  array('id_kabupaten' => '99','id_propinsi' => '10','kabupaten' => 'Cilacap'),
  array('id_kabupaten' => '100','id_propinsi' => '3','kabupaten' => 'Cilegon'),
  array('id_kabupaten' => '101','id_propinsi' => '9','kabupaten' => 'Cimahi'),
  array('id_kabupaten' => '102','id_propinsi' => '9','kabupaten' => 'Cirebon'),
  array('id_kabupaten' => '103','id_propinsi' => '33','kabupaten' => 'Dairi'),
  array('id_kabupaten' => '104','id_propinsi' => '23','kabupaten' => 'Deiyai (Deliyai)'),
  array('id_kabupaten' => '105','id_propinsi' => '33','kabupaten' => 'Deli Serdang'),
  array('id_kabupaten' => '106','id_propinsi' => '10','kabupaten' => 'Demak'),
  array('id_kabupaten' => '107','id_propinsi' => '1','kabupaten' => 'Denpasar'),
  array('id_kabupaten' => '108','id_propinsi' => '9','kabupaten' => 'Depok'),
  array('id_kabupaten' => '109','id_propinsi' => '31','kabupaten' => 'Dharmasraya'),
  array('id_kabupaten' => '110','id_propinsi' => '23','kabupaten' => 'Dogiyai'),
  array('id_kabupaten' => '111','id_propinsi' => '21','kabupaten' => 'Dompu'),
  array('id_kabupaten' => '112','id_propinsi' => '28','kabupaten' => 'Donggala'),
  array('id_kabupaten' => '113','id_propinsi' => '25','kabupaten' => 'Dumai'),
  array('id_kabupaten' => '114','id_propinsi' => '32','kabupaten' => 'Empat Lawang'),
  array('id_kabupaten' => '115','id_propinsi' => '22','kabupaten' => 'Ende'),
  array('id_kabupaten' => '116','id_propinsi' => '27','kabupaten' => 'Enrekang'),
  array('id_kabupaten' => '117','id_propinsi' => '23','kabupaten' => 'Fakfak'),
  array('id_kabupaten' => '118','id_propinsi' => '22','kabupaten' => 'Flores Timur'),
  array('id_kabupaten' => '119','id_propinsi' => '9','kabupaten' => 'Garut'),
  array('id_kabupaten' => '120','id_propinsi' => '20','kabupaten' => 'Gayo Lues'),
  array('id_kabupaten' => '121','id_propinsi' => '1','kabupaten' => 'Gianyar'),
  array('id_kabupaten' => '122','id_propinsi' => '7','kabupaten' => 'Gorontalo'),
  array('id_kabupaten' => '123','id_propinsi' => '7','kabupaten' => 'Gorontalo Utara'),
  array('id_kabupaten' => '124','id_propinsi' => '27','kabupaten' => 'Gowa'),
  array('id_kabupaten' => '125','id_propinsi' => '11','kabupaten' => 'Gresik'),
  array('id_kabupaten' => '126','id_propinsi' => '10','kabupaten' => 'Grobogan'),
  array('id_kabupaten' => '127','id_propinsi' => '5','kabupaten' => 'Gunung Kidul'),
  array('id_kabupaten' => '128','id_propinsi' => '14','kabupaten' => 'Gunung Mas'),
  array('id_kabupaten' => '129','id_propinsi' => '33','kabupaten' => 'Gunungsitoli'),
  array('id_kabupaten' => '130','id_propinsi' => '18','kabupaten' => 'Halmahera Barat'),
  array('id_kabupaten' => '131','id_propinsi' => '18','kabupaten' => 'Halmahera Selatan'),
  array('id_kabupaten' => '132','id_propinsi' => '18','kabupaten' => 'Halmahera Tengah'),
  array('id_kabupaten' => '133','id_propinsi' => '18','kabupaten' => 'Halmahera Timur'),
  array('id_kabupaten' => '134','id_propinsi' => '18','kabupaten' => 'Halmahera Utara'),
  array('id_kabupaten' => '135','id_propinsi' => '13','kabupaten' => 'Hulu Sungai Selatan'),
  array('id_kabupaten' => '136','id_propinsi' => '13','kabupaten' => 'Hulu Sungai Tengah'),
  array('id_kabupaten' => '137','id_propinsi' => '13','kabupaten' => 'Hulu Sungai Utara'),
  array('id_kabupaten' => '138','id_propinsi' => '33','kabupaten' => 'Humbang Hasundutan'),
  array('id_kabupaten' => '139','id_propinsi' => '25','kabupaten' => 'Indragiri Hilir'),
  array('id_kabupaten' => '140','id_propinsi' => '25','kabupaten' => 'Indragiri Hulu'),
  array('id_kabupaten' => '141','id_propinsi' => '9','kabupaten' => 'Indramayu'),
  array('id_kabupaten' => '142','id_propinsi' => '23','kabupaten' => 'Intan Jaya'),
  array('id_kabupaten' => '143','id_propinsi' => '6','kabupaten' => 'Jakarta Barat'),
  array('id_kabupaten' => '144','id_propinsi' => '6','kabupaten' => 'Jakarta Pusat'),
  array('id_kabupaten' => '145','id_propinsi' => '6','kabupaten' => 'Jakarta Selatan'),
  array('id_kabupaten' => '146','id_propinsi' => '6','kabupaten' => 'Jakarta Timur'),
  array('id_kabupaten' => '147','id_propinsi' => '6','kabupaten' => 'Jakarta Utara'),
  array('id_kabupaten' => '148','id_propinsi' => '8','kabupaten' => 'Jambi'),
  array('id_kabupaten' => '149','id_propinsi' => '23','kabupaten' => 'Jayapura'),
  array('id_kabupaten' => '150','id_propinsi' => '23','kabupaten' => 'Jayawijaya'),
  array('id_kabupaten' => '151','id_propinsi' => '11','kabupaten' => 'Jember'),
  array('id_kabupaten' => '152','id_propinsi' => '1','kabupaten' => 'Jembrana'),
  array('id_kabupaten' => '153','id_propinsi' => '27','kabupaten' => 'Jeneponto'),
  array('id_kabupaten' => '154','id_propinsi' => '10','kabupaten' => 'Jepara'),
  array('id_kabupaten' => '155','id_propinsi' => '11','kabupaten' => 'Jombang'),
  array('id_kabupaten' => '156','id_propinsi' => '23','kabupaten' => 'Kaimana'),
  array('id_kabupaten' => '157','id_propinsi' => '25','kabupaten' => 'Kampar'),
  array('id_kabupaten' => '158','id_propinsi' => '14','kabupaten' => 'Kapuas'),
  array('id_kabupaten' => '159','id_propinsi' => '12','kabupaten' => 'Kapuas Hulu'),
  array('id_kabupaten' => '160','id_propinsi' => '10','kabupaten' => 'Karanganyar'),
  array('id_kabupaten' => '161','id_propinsi' => '1','kabupaten' => 'Karangasem'),
  array('id_kabupaten' => '162','id_propinsi' => '9','kabupaten' => 'Karawang'),
  array('id_kabupaten' => '163','id_propinsi' => '16','kabupaten' => 'Karimun'),
  array('id_kabupaten' => '164','id_propinsi' => '33','kabupaten' => 'Karo'),
  array('id_kabupaten' => '165','id_propinsi' => '14','kabupaten' => 'Katingan'),
  array('id_kabupaten' => '166','id_propinsi' => '4','kabupaten' => 'Kaur'),
  array('id_kabupaten' => '167','id_propinsi' => '12','kabupaten' => 'Kayong Utara'),
  array('id_kabupaten' => '168','id_propinsi' => '10','kabupaten' => 'Kebumen'),
  array('id_kabupaten' => '169','id_propinsi' => '11','kabupaten' => 'Kediri'),
  array('id_kabupaten' => '170','id_propinsi' => '23','kabupaten' => 'Keerom'),
  array('id_kabupaten' => '171','id_propinsi' => '10','kabupaten' => 'Kendal'),
  array('id_kabupaten' => '172','id_propinsi' => '29','kabupaten' => 'Kendari'),
  array('id_kabupaten' => '173','id_propinsi' => '4','kabupaten' => 'Kepahiang'),
  array('id_kabupaten' => '174','id_propinsi' => '16','kabupaten' => 'Kepulauan Anambas'),
  array('id_kabupaten' => '175','id_propinsi' => '18','kabupaten' => 'Kepulauan Aru'),
  array('id_kabupaten' => '176','id_propinsi' => '31','kabupaten' => 'Kepulauan Mentawai'),
  array('id_kabupaten' => '177','id_propinsi' => '25','kabupaten' => 'Kepulauan Meranti'),
  array('id_kabupaten' => '178','id_propinsi' => '30','kabupaten' => 'Kepulauan Sangihe'),
  array('id_kabupaten' => '179','id_propinsi' => '6','kabupaten' => 'Kepulauan Seribu'),
  array('id_kabupaten' => '180','id_propinsi' => '30','kabupaten' => 'Kepulauan Siau Tagulandang Biaro (Sitaro)'),
  array('id_kabupaten' => '181','id_propinsi' => '18','kabupaten' => 'Kepulauan Sula'),
  array('id_kabupaten' => '182','id_propinsi' => '30','kabupaten' => 'Kepulauan Talaud'),
  array('id_kabupaten' => '183','id_propinsi' => '23','kabupaten' => 'Kepulauan Yapen (Yapen Waropen)'),
  array('id_kabupaten' => '184','id_propinsi' => '8','kabupaten' => 'Kerinci'),
  array('id_kabupaten' => '185','id_propinsi' => '12','kabupaten' => 'Ketapang'),
  array('id_kabupaten' => '186','id_propinsi' => '10','kabupaten' => 'Klaten'),
  array('id_kabupaten' => '187','id_propinsi' => '1','kabupaten' => 'Klungkung'),
  array('id_kabupaten' => '188','id_propinsi' => '29','kabupaten' => 'Kolaka'),
  array('id_kabupaten' => '189','id_propinsi' => '29','kabupaten' => 'Kolaka Utara'),
  array('id_kabupaten' => '190','id_propinsi' => '29','kabupaten' => 'Konawe'),
  array('id_kabupaten' => '191','id_propinsi' => '29','kabupaten' => 'Konawe Selatan'),
  array('id_kabupaten' => '192','id_propinsi' => '29','kabupaten' => 'Konawe Utara'),
  array('id_kabupaten' => '193','id_propinsi' => '13','kabupaten' => 'Kotabaru'),
  array('id_kabupaten' => '194','id_propinsi' => '30','kabupaten' => 'Kotamobagu'),
  array('id_kabupaten' => '195','id_propinsi' => '14','kabupaten' => 'Kotawaringin Barat'),
  array('id_kabupaten' => '196','id_propinsi' => '14','kabupaten' => 'Kotawaringin Timur'),
  array('id_kabupaten' => '197','id_propinsi' => '25','kabupaten' => 'Kuantan Singingi'),
  array('id_kabupaten' => '198','id_propinsi' => '12','kabupaten' => 'Kubu Raya'),
  array('id_kabupaten' => '199','id_propinsi' => '10','kabupaten' => 'Kudus'),
  array('id_kabupaten' => '200','id_propinsi' => '5','kabupaten' => 'Kulon Progo'),
  array('id_kabupaten' => '201','id_propinsi' => '9','kabupaten' => 'Kuningan'),
  array('id_kabupaten' => '202','id_propinsi' => '22','kabupaten' => 'Kupang'),
  array('id_kabupaten' => '203','id_propinsi' => '15','kabupaten' => 'Kutai Barat'),
  array('id_kabupaten' => '204','id_propinsi' => '15','kabupaten' => 'Kutai Kartanegara'),
  array('id_kabupaten' => '205','id_propinsi' => '15','kabupaten' => 'Kutai Timur'),
  array('id_kabupaten' => '206','id_propinsi' => '33','kabupaten' => 'Labuhan Batu'),
  array('id_kabupaten' => '207','id_propinsi' => '33','kabupaten' => 'Labuhan Batu Selatan'),
  array('id_kabupaten' => '208','id_propinsi' => '33','kabupaten' => 'Labuhan Batu Utara'),
  array('id_kabupaten' => '209','id_propinsi' => '32','kabupaten' => 'Lahat'),
  array('id_kabupaten' => '210','id_propinsi' => '14','kabupaten' => 'Lamandau'),
  array('id_kabupaten' => '211','id_propinsi' => '11','kabupaten' => 'Lamongan'),
  array('id_kabupaten' => '212','id_propinsi' => '17','kabupaten' => 'Lampung Barat'),
  array('id_kabupaten' => '213','id_propinsi' => '17','kabupaten' => 'Lampung Selatan'),
  array('id_kabupaten' => '214','id_propinsi' => '17','kabupaten' => 'Lampung Tengah'),
  array('id_kabupaten' => '215','id_propinsi' => '17','kabupaten' => 'Lampung Timur'),
  array('id_kabupaten' => '216','id_propinsi' => '17','kabupaten' => 'Lampung Utara'),
  array('id_kabupaten' => '217','id_propinsi' => '12','kabupaten' => 'Landak'),
  array('id_kabupaten' => '218','id_propinsi' => '33','kabupaten' => 'Langkat'),
  array('id_kabupaten' => '219','id_propinsi' => '20','kabupaten' => 'Langsa'),
  array('id_kabupaten' => '220','id_propinsi' => '23','kabupaten' => 'Lanny Jaya'),
  array('id_kabupaten' => '221','id_propinsi' => '3','kabupaten' => 'Lebak'),
  array('id_kabupaten' => '222','id_propinsi' => '4','kabupaten' => 'Lebong'),
  array('id_kabupaten' => '223','id_propinsi' => '22','kabupaten' => 'Lembata'),
  array('id_kabupaten' => '224','id_propinsi' => '20','kabupaten' => 'Lhokseumawe'),
  array('id_kabupaten' => '225','id_propinsi' => '31','kabupaten' => 'Lima Puluh Koto/Kota'),
  array('id_kabupaten' => '226','id_propinsi' => '16','kabupaten' => 'Lingga'),
  array('id_kabupaten' => '227','id_propinsi' => '21','kabupaten' => 'Lombok Barat'),
  array('id_kabupaten' => '228','id_propinsi' => '21','kabupaten' => 'Lombok Tengah'),
  array('id_kabupaten' => '229','id_propinsi' => '21','kabupaten' => 'Lombok Timur'),
  array('id_kabupaten' => '230','id_propinsi' => '21','kabupaten' => 'Lombok Utara'),
  array('id_kabupaten' => '231','id_propinsi' => '32','kabupaten' => 'Lubuk Linggau'),
  array('id_kabupaten' => '232','id_propinsi' => '11','kabupaten' => 'Lumajang'),
  array('id_kabupaten' => '233','id_propinsi' => '27','kabupaten' => 'Luwu'),
  array('id_kabupaten' => '234','id_propinsi' => '27','kabupaten' => 'Luwu Timur'),
  array('id_kabupaten' => '235','id_propinsi' => '27','kabupaten' => 'Luwu Utara'),
  array('id_kabupaten' => '236','id_propinsi' => '11','kabupaten' => 'Madiun'),
  array('id_kabupaten' => '237','id_propinsi' => '10','kabupaten' => 'Magelang'),
  array('id_kabupaten' => '238','id_propinsi' => '11','kabupaten' => 'Magetan'),
  array('id_kabupaten' => '239','id_propinsi' => '9','kabupaten' => 'Majalengka'),
  array('id_kabupaten' => '240','id_propinsi' => '26','kabupaten' => 'Majene'),
  array('id_kabupaten' => '241','id_propinsi' => '27','kabupaten' => 'Makassar'),
  array('id_kabupaten' => '242','id_propinsi' => '11','kabupaten' => 'Malang'),
  array('id_kabupaten' => '243','id_propinsi' => '34','kabupaten' => 'Malinau'),
  array('id_kabupaten' => '244','id_propinsi' => '18','kabupaten' => 'Maluku Barat Daya'),
  array('id_kabupaten' => '245','id_propinsi' => '18','kabupaten' => 'Maluku Tengah'),
  array('id_kabupaten' => '246','id_propinsi' => '18','kabupaten' => 'Maluku Tenggara'),
  array('id_kabupaten' => '247','id_propinsi' => '18','kabupaten' => 'Maluku Tenggara Barat'),
  array('id_kabupaten' => '248','id_propinsi' => '26','kabupaten' => 'Mamasa'),
  array('id_kabupaten' => '249','id_propinsi' => '23','kabupaten' => 'Mamberamo Raya'),
  array('id_kabupaten' => '250','id_propinsi' => '23','kabupaten' => 'Mamberamo Tengah'),
  array('id_kabupaten' => '251','id_propinsi' => '26','kabupaten' => 'Mamuju'),
  array('id_kabupaten' => '252','id_propinsi' => '26','kabupaten' => 'Mamuju Utara'),
  array('id_kabupaten' => '253','id_propinsi' => '30','kabupaten' => 'Manado'),
  array('id_kabupaten' => '254','id_propinsi' => '33','kabupaten' => 'Mandailing Natal'),
  array('id_kabupaten' => '255','id_propinsi' => '22','kabupaten' => 'Manggarai'),
  array('id_kabupaten' => '256','id_propinsi' => '22','kabupaten' => 'Manggarai Barat'),
  array('id_kabupaten' => '257','id_propinsi' => '22','kabupaten' => 'Manggarai Timur'),
  array('id_kabupaten' => '258','id_propinsi' => '23','kabupaten' => 'Manokwari'),
  array('id_kabupaten' => '259','id_propinsi' => '23','kabupaten' => 'Mappi'),
  array('id_kabupaten' => '260','id_propinsi' => '27','kabupaten' => 'Maros'),
  array('id_kabupaten' => '261','id_propinsi' => '21','kabupaten' => 'Mataram'),
  array('id_kabupaten' => '262','id_propinsi' => '23','kabupaten' => 'Maybrat'),
  array('id_kabupaten' => '263','id_propinsi' => '33','kabupaten' => 'Medan'),
  array('id_kabupaten' => '264','id_propinsi' => '12','kabupaten' => 'Melawi'),
  array('id_kabupaten' => '265','id_propinsi' => '8','kabupaten' => 'Merangin'),
  array('id_kabupaten' => '266','id_propinsi' => '23','kabupaten' => 'Merauke'),
  array('id_kabupaten' => '267','id_propinsi' => '17','kabupaten' => 'Mesuji'),
  array('id_kabupaten' => '268','id_propinsi' => '17','kabupaten' => 'Metro'),
  array('id_kabupaten' => '269','id_propinsi' => '23','kabupaten' => 'Mimika'),
  array('id_kabupaten' => '270','id_propinsi' => '30','kabupaten' => 'Minahasa'),
  array('id_kabupaten' => '271','id_propinsi' => '30','kabupaten' => 'Minahasa Selatan'),
  array('id_kabupaten' => '272','id_propinsi' => '30','kabupaten' => 'Minahasa Tenggara'),
  array('id_kabupaten' => '273','id_propinsi' => '30','kabupaten' => 'Minahasa Utara'),
  array('id_kabupaten' => '274','id_propinsi' => '11','kabupaten' => 'Mojokerto'),
  array('id_kabupaten' => '275','id_propinsi' => '28','kabupaten' => 'Morowali'),
  array('id_kabupaten' => '276','id_propinsi' => '32','kabupaten' => 'Muara Enim'),
  array('id_kabupaten' => '277','id_propinsi' => '8','kabupaten' => 'Muaro Jambi'),
  array('id_kabupaten' => '278','id_propinsi' => '4','kabupaten' => 'Muko Muko'),
  array('id_kabupaten' => '279','id_propinsi' => '29','kabupaten' => 'Muna'),
  array('id_kabupaten' => '280','id_propinsi' => '14','kabupaten' => 'Murung Raya'),
  array('id_kabupaten' => '281','id_propinsi' => '32','kabupaten' => 'Musi Banyuasin'),
  array('id_kabupaten' => '282','id_propinsi' => '32','kabupaten' => 'Musi Rawas'),
  array('id_kabupaten' => '283','id_propinsi' => '23','kabupaten' => 'Nabire'),
  array('id_kabupaten' => '284','id_propinsi' => '20','kabupaten' => 'Nagan Raya'),
  array('id_kabupaten' => '285','id_propinsi' => '22','kabupaten' => 'Nagekeo'),
  array('id_kabupaten' => '286','id_propinsi' => '16','kabupaten' => 'Natuna'),
  array('id_kabupaten' => '287','id_propinsi' => '23','kabupaten' => 'Nduga'),
  array('id_kabupaten' => '288','id_propinsi' => '22','kabupaten' => 'Ngada'),
  array('id_kabupaten' => '289','id_propinsi' => '11','kabupaten' => 'Nganjuk'),
  array('id_kabupaten' => '290','id_propinsi' => '11','kabupaten' => 'Ngawi'),
  array('id_kabupaten' => '291','id_propinsi' => '33','kabupaten' => 'Nias'),
  array('id_kabupaten' => '292','id_propinsi' => '33','kabupaten' => 'Nias Barat'),
  array('id_kabupaten' => '293','id_propinsi' => '33','kabupaten' => 'Nias Selatan'),
  array('id_kabupaten' => '294','id_propinsi' => '33','kabupaten' => 'Nias Utara'),
  array('id_kabupaten' => '295','id_propinsi' => '34','kabupaten' => 'Nunukan'),
  array('id_kabupaten' => '296','id_propinsi' => '32','kabupaten' => 'Ogan Ilir'),
  array('id_kabupaten' => '297','id_propinsi' => '32','kabupaten' => 'Ogan Komering Ilir'),
  array('id_kabupaten' => '298','id_propinsi' => '32','kabupaten' => 'Ogan Komering Ulu'),
  array('id_kabupaten' => '299','id_propinsi' => '32','kabupaten' => 'Ogan Komering Ulu Selatan'),
  array('id_kabupaten' => '300','id_propinsi' => '32','kabupaten' => 'Ogan Komering Ulu Timur'),
  array('id_kabupaten' => '301','id_propinsi' => '11','kabupaten' => 'Pacitan'),
  array('id_kabupaten' => '302','id_propinsi' => '31','kabupaten' => 'Padang'),
  array('id_kabupaten' => '303','id_propinsi' => '33','kabupaten' => 'Padang Lawas'),
  array('id_kabupaten' => '304','id_propinsi' => '33','kabupaten' => 'Padang Lawas Utara'),
  array('id_kabupaten' => '305','id_propinsi' => '31','kabupaten' => 'Padang Panjang'),
  array('id_kabupaten' => '306','id_propinsi' => '31','kabupaten' => 'Padang Pariaman'),
  array('id_kabupaten' => '307','id_propinsi' => '33','kabupaten' => 'Padang Sidempuan'),
  array('id_kabupaten' => '308','id_propinsi' => '32','kabupaten' => 'Pagar Alam'),
  array('id_kabupaten' => '309','id_propinsi' => '33','kabupaten' => 'Pakpak Bharat'),
  array('id_kabupaten' => '310','id_propinsi' => '14','kabupaten' => 'Palangka Raya'),
  array('id_kabupaten' => '311','id_propinsi' => '32','kabupaten' => 'Palembang'),
  array('id_kabupaten' => '312','id_propinsi' => '27','kabupaten' => 'Palopo'),
  array('id_kabupaten' => '313','id_propinsi' => '28','kabupaten' => 'Palu'),
  array('id_kabupaten' => '314','id_propinsi' => '11','kabupaten' => 'Pamekasan'),
  array('id_kabupaten' => '315','id_propinsi' => '3','kabupaten' => 'Pandeglang'),
  array('id_kabupaten' => '316','id_propinsi' => '27','kabupaten' => 'Pangkajene Kepulauan'),
  array('id_kabupaten' => '317','id_propinsi' => '2','kabupaten' => 'Pangkal Pinang'),
  array('id_kabupaten' => '318','id_propinsi' => '23','kabupaten' => 'Paniai'),
  array('id_kabupaten' => '319','id_propinsi' => '27','kabupaten' => 'Parepare'),
  array('id_kabupaten' => '320','id_propinsi' => '31','kabupaten' => 'Pariaman'),
  array('id_kabupaten' => '321','id_propinsi' => '28','kabupaten' => 'Parigi Moutong'),
  array('id_kabupaten' => '322','id_propinsi' => '31','kabupaten' => 'Pasaman'),
  array('id_kabupaten' => '323','id_propinsi' => '31','kabupaten' => 'Pasaman Barat'),
  array('id_kabupaten' => '324','id_propinsi' => '15','kabupaten' => 'Paser'),
  array('id_kabupaten' => '325','id_propinsi' => '11','kabupaten' => 'Pasuruan'),
  array('id_kabupaten' => '326','id_propinsi' => '10','kabupaten' => 'Pati'),
  array('id_kabupaten' => '327','id_propinsi' => '31','kabupaten' => 'Payakumbuh'),
  array('id_kabupaten' => '328','id_propinsi' => '23','kabupaten' => 'Pegunungan Bintang'),
  array('id_kabupaten' => '329','id_propinsi' => '10','kabupaten' => 'Pekalongan'),
  array('id_kabupaten' => '330','id_propinsi' => '25','kabupaten' => 'Pekanbaru'),
  array('id_kabupaten' => '331','id_propinsi' => '25','kabupaten' => 'Pelalawan'),
  array('id_kabupaten' => '332','id_propinsi' => '10','kabupaten' => 'Pemalang'),
  array('id_kabupaten' => '333','id_propinsi' => '33','kabupaten' => 'Pematang Siantar'),
  array('id_kabupaten' => '334','id_propinsi' => '15','kabupaten' => 'Penajam Paser Utara'),
  array('id_kabupaten' => '335','id_propinsi' => '17','kabupaten' => 'Pesawaran'),
  array('id_kabupaten' => '336','id_propinsi' => '31','kabupaten' => 'Pesisir Selatan'),
  array('id_kabupaten' => '337','id_propinsi' => '20','kabupaten' => 'Pidie'),
  array('id_kabupaten' => '338','id_propinsi' => '20','kabupaten' => 'Pidie Jaya'),
  array('id_kabupaten' => '339','id_propinsi' => '27','kabupaten' => 'Pinrang'),
  array('id_kabupaten' => '340','id_propinsi' => '7','kabupaten' => 'Pohuwato'),
  array('id_kabupaten' => '341','id_propinsi' => '26','kabupaten' => 'Polewali Mandar'),
  array('id_kabupaten' => '342','id_propinsi' => '11','kabupaten' => 'Ponorogo'),
  array('id_kabupaten' => '343','id_propinsi' => '12','kabupaten' => 'Pontianak'),
  array('id_kabupaten' => '344','id_propinsi' => '28','kabupaten' => 'Poso'),
  array('id_kabupaten' => '345','id_propinsi' => '32','kabupaten' => 'Prabumulih'),
  array('id_kabupaten' => '346','id_propinsi' => '17','kabupaten' => 'Pringsewu'),
  array('id_kabupaten' => '347','id_propinsi' => '11','kabupaten' => 'Probolinggo'),
  array('id_kabupaten' => '348','id_propinsi' => '14','kabupaten' => 'Pulang Pisau'),
  array('id_kabupaten' => '349','id_propinsi' => '18','kabupaten' => 'Pulau Morotai'),
  array('id_kabupaten' => '350','id_propinsi' => '23','kabupaten' => 'Puncak'),
  array('id_kabupaten' => '351','id_propinsi' => '23','kabupaten' => 'Puncak Jaya'),
  array('id_kabupaten' => '352','id_propinsi' => '10','kabupaten' => 'Purbalingga'),
  array('id_kabupaten' => '353','id_propinsi' => '9','kabupaten' => 'Purwakarta'),
  array('id_kabupaten' => '354','id_propinsi' => '10','kabupaten' => 'Purworejo'),
  array('id_kabupaten' => '355','id_propinsi' => '23','kabupaten' => 'Raja Ampat'),
  array('id_kabupaten' => '356','id_propinsi' => '4','kabupaten' => 'Rejang Lebong'),
  array('id_kabupaten' => '357','id_propinsi' => '10','kabupaten' => 'Rembang'),
  array('id_kabupaten' => '358','id_propinsi' => '25','kabupaten' => 'Rokan Hilir'),
  array('id_kabupaten' => '359','id_propinsi' => '25','kabupaten' => 'Rokan Hulu'),
  array('id_kabupaten' => '360','id_propinsi' => '22','kabupaten' => 'Rote Ndao'),
  array('id_kabupaten' => '361','id_propinsi' => '20','kabupaten' => 'Sabang'),
  array('id_kabupaten' => '362','id_propinsi' => '22','kabupaten' => 'Sabu Raijua'),
  array('id_kabupaten' => '363','id_propinsi' => '10','kabupaten' => 'Salatiga'),
  array('id_kabupaten' => '364','id_propinsi' => '15','kabupaten' => 'Samarinda'),
  array('id_kabupaten' => '365','id_propinsi' => '12','kabupaten' => 'Sambas'),
  array('id_kabupaten' => '366','id_propinsi' => '33','kabupaten' => 'Samosir'),
  array('id_kabupaten' => '367','id_propinsi' => '11','kabupaten' => 'Sampang'),
  array('id_kabupaten' => '368','id_propinsi' => '12','kabupaten' => 'Sanggau'),
  array('id_kabupaten' => '369','id_propinsi' => '23','kabupaten' => 'Sarmi'),
  array('id_kabupaten' => '370','id_propinsi' => '8','kabupaten' => 'Sarolangun'),
  array('id_kabupaten' => '371','id_propinsi' => '31','kabupaten' => 'Sawah Lunto'),
  array('id_kabupaten' => '372','id_propinsi' => '12','kabupaten' => 'Sekadau'),
  array('id_kabupaten' => '373','id_propinsi' => '27','kabupaten' => 'Selayar (Kepulauan Selayar)'),
  array('id_kabupaten' => '374','id_propinsi' => '4','kabupaten' => 'Seluma'),
  array('id_kabupaten' => '375','id_propinsi' => '10','kabupaten' => 'Semarang'),
  array('id_kabupaten' => '376','id_propinsi' => '18','kabupaten' => 'Seram Bagian Barat'),
  array('id_kabupaten' => '377','id_propinsi' => '18','kabupaten' => 'Seram Bagian Timur'),
  array('id_kabupaten' => '378','id_propinsi' => '3','kabupaten' => 'Serang'),
  array('id_kabupaten' => '379','id_propinsi' => '33','kabupaten' => 'Serdang Bedagai'),
  array('id_kabupaten' => '380','id_propinsi' => '14','kabupaten' => 'Seruyan'),
  array('id_kabupaten' => '381','id_propinsi' => '25','kabupaten' => 'Siak'),
  array('id_kabupaten' => '382','id_propinsi' => '33','kabupaten' => 'Sibolga'),
  array('id_kabupaten' => '383','id_propinsi' => '27','kabupaten' => 'Sidenreng Rappang/Rapang'),
  array('id_kabupaten' => '384','id_propinsi' => '11','kabupaten' => 'Sidoarjo'),
  array('id_kabupaten' => '385','id_propinsi' => '28','kabupaten' => 'Sigi'),
  array('id_kabupaten' => '386','id_propinsi' => '31','kabupaten' => 'Sijunjung (Sawah Lunto Sijunjung)'),
  array('id_kabupaten' => '387','id_propinsi' => '22','kabupaten' => 'Sikka'),
  array('id_kabupaten' => '388','id_propinsi' => '33','kabupaten' => 'Simalungun'),
  array('id_kabupaten' => '389','id_propinsi' => '20','kabupaten' => 'Simeulue'),
  array('id_kabupaten' => '390','id_propinsi' => '12','kabupaten' => 'Singkawang'),
  array('id_kabupaten' => '391','id_propinsi' => '27','kabupaten' => 'Sinjai'),
  array('id_kabupaten' => '392','id_propinsi' => '12','kabupaten' => 'Sintang'),
  array('id_kabupaten' => '393','id_propinsi' => '11','kabupaten' => 'Situbondo'),
  array('id_kabupaten' => '394','id_propinsi' => '5','kabupaten' => 'Sleman'),
  array('id_kabupaten' => '395','id_propinsi' => '31','kabupaten' => 'Solok'),
  array('id_kabupaten' => '396','id_propinsi' => '31','kabupaten' => 'Solok Selatan'),
  array('id_kabupaten' => '397','id_propinsi' => '27','kabupaten' => 'Soppeng'),
  array('id_kabupaten' => '398','id_propinsi' => '23','kabupaten' => 'Sorong'),
  array('id_kabupaten' => '399','id_propinsi' => '23','kabupaten' => 'Sorong Selatan'),
  array('id_kabupaten' => '400','id_propinsi' => '10','kabupaten' => 'Sragen'),
  array('id_kabupaten' => '401','id_propinsi' => '9','kabupaten' => 'Subang'),
  array('id_kabupaten' => '402','id_propinsi' => '20','kabupaten' => 'Subulussalam'),
  array('id_kabupaten' => '403','id_propinsi' => '9','kabupaten' => 'Sukabumi'),
  array('id_kabupaten' => '404','id_propinsi' => '14','kabupaten' => 'Sukamara'),
  array('id_kabupaten' => '405','id_propinsi' => '10','kabupaten' => 'Sukoharjo'),
  array('id_kabupaten' => '406','id_propinsi' => '22','kabupaten' => 'Sumba Barat'),
  array('id_kabupaten' => '407','id_propinsi' => '22','kabupaten' => 'Sumba Barat Daya'),
  array('id_kabupaten' => '408','id_propinsi' => '22','kabupaten' => 'Sumba Tengah'),
  array('id_kabupaten' => '409','id_propinsi' => '22','kabupaten' => 'Sumba Timur'),
  array('id_kabupaten' => '410','id_propinsi' => '21','kabupaten' => 'Sumbawa'),
  array('id_kabupaten' => '411','id_propinsi' => '21','kabupaten' => 'Sumbawa Barat'),
  array('id_kabupaten' => '412','id_propinsi' => '9','kabupaten' => 'Sumedang'),
  array('id_kabupaten' => '413','id_propinsi' => '11','kabupaten' => 'Sumenep'),
  array('id_kabupaten' => '414','id_propinsi' => '8','kabupaten' => 'Sungaipenuh'),
  array('id_kabupaten' => '415','id_propinsi' => '23','kabupaten' => 'Supiori'),
  array('id_kabupaten' => '416','id_propinsi' => '11','kabupaten' => 'Surabaya'),
  array('id_kabupaten' => '417','id_propinsi' => '10','kabupaten' => 'Surakarta (Solo)'),
  array('id_kabupaten' => '418','id_propinsi' => '13','kabupaten' => 'Tabalong'),
  array('id_kabupaten' => '419','id_propinsi' => '1','kabupaten' => 'Tabanan'),
  array('id_kabupaten' => '420','id_propinsi' => '27','kabupaten' => 'Takalar'),
  array('id_kabupaten' => '421','id_propinsi' => '23','kabupaten' => 'Tambrauw'),
  array('id_kabupaten' => '422','id_propinsi' => '34','kabupaten' => 'Tana Tidung'),
  array('id_kabupaten' => '423','id_propinsi' => '27','kabupaten' => 'Tana Toraja'),
  array('id_kabupaten' => '424','id_propinsi' => '13','kabupaten' => 'Tanah Bumbu'),
  array('id_kabupaten' => '425','id_propinsi' => '31','kabupaten' => 'Tanah Datar'),
  array('id_kabupaten' => '426','id_propinsi' => '13','kabupaten' => 'Tanah Laut'),
  array('id_kabupaten' => '427','id_propinsi' => '3','kabupaten' => 'Tangerang'),
  array('id_kabupaten' => '428','id_propinsi' => '3','kabupaten' => 'Tangerang Selatan'),
  array('id_kabupaten' => '429','id_propinsi' => '17','kabupaten' => 'Tanggamus'),
  array('id_kabupaten' => '430','id_propinsi' => '33','kabupaten' => 'Tanjung Balai'),
  array('id_kabupaten' => '431','id_propinsi' => '8','kabupaten' => 'Tanjung Jabung Barat'),
  array('id_kabupaten' => '432','id_propinsi' => '8','kabupaten' => 'Tanjung Jabung Timur'),
  array('id_kabupaten' => '433','id_propinsi' => '16','kabupaten' => 'Tanjung Pinang'),
  array('id_kabupaten' => '434','id_propinsi' => '33','kabupaten' => 'Tapanuli Selatan'),
  array('id_kabupaten' => '435','id_propinsi' => '33','kabupaten' => 'Tapanuli Tengah'),
  array('id_kabupaten' => '436','id_propinsi' => '33','kabupaten' => 'Tapanuli Utara'),
  array('id_kabupaten' => '437','id_propinsi' => '13','kabupaten' => 'Tapin'),
  array('id_kabupaten' => '438','id_propinsi' => '34','kabupaten' => 'Tarakan'),
  array('id_kabupaten' => '439','id_propinsi' => '9','kabupaten' => 'Tasikmalaya'),
  array('id_kabupaten' => '440','id_propinsi' => '33','kabupaten' => 'Tebing Tinggi'),
  array('id_kabupaten' => '441','id_propinsi' => '8','kabupaten' => 'Tebo'),
  array('id_kabupaten' => '442','id_propinsi' => '10','kabupaten' => 'Tegal'),
  array('id_kabupaten' => '443','id_propinsi' => '23','kabupaten' => 'Teluk Bintuni'),
  array('id_kabupaten' => '444','id_propinsi' => '23','kabupaten' => 'Teluk Wondama'),
  array('id_kabupaten' => '445','id_propinsi' => '10','kabupaten' => 'Temanggung'),
  array('id_kabupaten' => '446','id_propinsi' => '18','kabupaten' => 'Ternate'),
  array('id_kabupaten' => '447','id_propinsi' => '18','kabupaten' => 'Tidore Kepulauan'),
  array('id_kabupaten' => '448','id_propinsi' => '22','kabupaten' => 'Timor Tengah Selatan'),
  array('id_kabupaten' => '449','id_propinsi' => '22','kabupaten' => 'Timor Tengah Utara'),
  array('id_kabupaten' => '450','id_propinsi' => '33','kabupaten' => 'Toba Samosir'),
  array('id_kabupaten' => '451','id_propinsi' => '28','kabupaten' => 'Tojo Una-Una'),
  array('id_kabupaten' => '452','id_propinsi' => '28','kabupaten' => 'Toli-Toli'),
  array('id_kabupaten' => '453','id_propinsi' => '23','kabupaten' => 'Tolikara'),
  array('id_kabupaten' => '454','id_propinsi' => '30','kabupaten' => 'Tomohon'),
  array('id_kabupaten' => '455','id_propinsi' => '27','kabupaten' => 'Toraja Utara'),
  array('id_kabupaten' => '456','id_propinsi' => '11','kabupaten' => 'Trenggalek'),
  array('id_kabupaten' => '457','id_propinsi' => '18','kabupaten' => 'Tual'),
  array('id_kabupaten' => '458','id_propinsi' => '11','kabupaten' => 'Tuban'),
  array('id_kabupaten' => '459','id_propinsi' => '17','kabupaten' => 'Tulang Bawang'),
  array('id_kabupaten' => '460','id_propinsi' => '17','kabupaten' => 'Tulang Bawang Barat'),
  array('id_kabupaten' => '461','id_propinsi' => '11','kabupaten' => 'Tulungagung'),
  array('id_kabupaten' => '462','id_propinsi' => '27','kabupaten' => 'Wajo'),
  array('id_kabupaten' => '463','id_propinsi' => '29','kabupaten' => 'Wakatobi'),
  array('id_kabupaten' => '464','id_propinsi' => '23','kabupaten' => 'Waropen'),
  array('id_kabupaten' => '465','id_propinsi' => '17','kabupaten' => 'Way Kanan'),
  array('id_kabupaten' => '466','id_propinsi' => '10','kabupaten' => 'Wonogiri'),
  array('id_kabupaten' => '467','id_propinsi' => '10','kabupaten' => 'Wonosobo'),
  array('id_kabupaten' => '468','id_propinsi' => '23','kabupaten' => 'Yahukimo'),
  array('id_kabupaten' => '469','id_propinsi' => '23','kabupaten' => 'Yalimo'),
  array('id_kabupaten' => '470','id_propinsi' => '5','kabupaten' => 'Yogyakarta'),
  array('id_kabupaten' => '471','id_propinsi' => '34','kabupaten' => 'Bulungan')
);
